### ISSUE TITLE
Two payment methods, one doesn't work, one "works" w/o taking any CC info

### ISSUE THREAD

**Issue by bfellows37** [merchantprotocol/Magento-Paytrace-Payment-Gateway#1]
First off, thanks for this module.

I downloaded it and installed on my Magento CE 1.9.0.1 sandbox deployment and enabled the method. When I try to check out, there are two of the same [Credit Card (L3)] methods to select from.

Neither displays a form for entering CC info. Selecting the first and clicking continue alerts that the expiration date is incorrect and does not allow checkout to proceed. The second allows checkout to proceed without collecting any credit card info.

Was wondering if you had any suggestions.

![image](https://cloud.githubusercontent.com/assets/10556249/6072170/5adc7b84-ad53-11e4-8af2-a3af87e64eb7.png)

**Comment by bfellows37** [comment]
I figured out why it wasn't displaying the form. Looks like the file structure doesn't match what the module specifies or something. I get this error in the system.log:

"2015-02-13T23:46:51+00:00 CRIT (2): Not valid template file:frontend/base/default/template/level3/form/cc.phtml"

I located the level3 folder located in frontend/default/default/template. Moving it to frontend/base/default/template seems to have solved the "missing form" issue and it no longer errors on the log.

Still getting two forms though...

**Comment by netstepinc** [comment]
Thank you for this extension. I installed it, and it wouldn't work because my password was too long. That wasn't the fault of the extension but rather an issue with PayTrace account credentials.
However, I'm seeing two payment forms.
As far as I know we don't have any customer group payment selector installed so I don't know how to turn that off. I hope someone can provide some suggestions because the double form gets jacked up and fails easily.

**Comment by netstepinc** [comment]
Would it be possible to obtain support for this extension?

**Comment by netstepinc** [comment]
I don't understand why this payment module shows up twice when I enable it.
![image](https://cloud.githubusercontent.com/assets/1270612/11085219/a35ed926-87f8-11e5-861f-e6953ef7daae.png)

**Comment by ericfox83** [comment]
Hi @netstepinc, I believe you'll need to comment out the saved card section in app/design/frontend/default/default/template/level3/form/cc.phtml. 

Give that a try. I'm currently using this extension on my website and I have the Purchase Order Number section and the saved card section commented out.

**Comment by netstepinc** [comment]
@ericfox83 thank you so much for pointing me in this direction. The developer appears to no longer support the extension. 
However, there are not two instances of the form in cc.phtml.
Instead, something else repeats it.
I've removed everything I could see related to "saved" cards and it's still doubled.
...some days I wish I was smarter. :)

**Comment by netstepinc** [comment]
After rooting around in the rest of the extension for a while I gave up and used CSS to hide the first form...BUT then the form will not submit. I don't get it.
```
<style type="text/css">
#dt_method_revolution_saved,#dd_method_revolution_saved{display:none !important;}
</style>
```

**Comment by bfellows37** [comment]
I did some looking when I was trying to figure that out. It's been a few
months so bear with me. As far as I can tell, Magento doesn't like have two
different payment forms in one extension. I wrote my own paytrace extension
from scratch that was working fine for auth-only until my company decided
to scrap it all in favor of Wells Fargo's solution. I'll publish it on
github when I get an opportunity to review the code for proprietary stuff.

**Comment by netstepinc** [comment]
#bfellows37 THAT WOULD BE AWESOME!

Failure on this isn't an option for me...
We've got customers abandoning carts because they don't understand the payment page so I'm getting chewed up by my boss...who implemented PayTrace...go figure. :)

I'm just not Mage/Zend savvy enough to sort this out on my own, so I truly appreciate anything you have to offer. I don't expect something for nothing, and I value your time so let me know how I can compensate you.

**Comment by bfellows37** [comment]
Hey Sam I sent you an email at the address listed in your github profile.

**Comment by ericfox83** [comment]
Hey guys, did y'all get this all figured out? If not, I can send you my modified version of this extension that I'm using successfully on my websites.

**Comment by netstepinc** [comment]
#ericfox83 I'd certainly like to see your tweaked version. #bfellows37 has provided an alternative, but I'd like to have a plan B just in case because my situation is getting pretty urgent. I'll be working on Plan A today.

**Comment by Jonathonbyrd** [comment]
Hello all. The reason that there are two payment options displaying is because the second option is for saved cards. Eric, why don't you send me the code that you have and I'll get this fixed up.

**Comment by ericfox83** [comment]
Hey everyone, I just sent Jonathon the package that I modified to make this extension work seamlessly. I think he's going to post it or do something with it for everyone.

Just an fyi, i removed the Purchase Order segment from the extension, since it wasn't needed for my website. 

The only I have, which I'm not sure if it's from this extension, is that in PayTrace, the 2 digit state code shows up as the first 2 letters of the state. So for example Arizona shows up as AR instead of AZ. It's really not a big deal, but when we process credits for returns, they sometimes have to fix the state codes.

**Comment by Jonathonbyrd** [comment]
Hello Everybody. I've Fixed the many issues mentioned in this thread. The plugin was originally built alongside a second extension, a recurring order extension, that I have not yet released. The master branch should be ready to go.

## Upgrading from v1.0 to v2.0.0

 - Please remove the v1.0 files from your system. The new release, v2.0.0, has a different naming structure that is not compatible with v1.0.
 - Copy over everything from the Step1 folder
 - Copy over everything from the Step2 folder
 - Access your administrative area and the plugin will run the installation process.

If you have any issues at all, please open a github issue.
