### ISSUE TITLE
PayTrace forcing to use CC

### ISSUE THREAD

**Issue by creativewebgirl** [merchantprotocol/Magento-Paytrace-Payment-Gateway#3]
Hello, This is just great however, if a client chooses to use Purchase Order, it still forces them to add credit card info.  If you click credit card the click purchase order it will sometimes let you get by this but for the most part, it forces you to add CC info.

**Comment by Jonathonbyrd** [comment]
The credit card information is always required. The purchase order is only required when the company buying the goods has issued a purchase order for their buyer to make the purchase.

The buyer cannot checkout with the purchase order number alone. There's a native module that would provide this functionality if you wish.

The reason that the purchase order field is optional in this module, is due to the fact that when entered it accomplishes all requirements for PCI Compliant Level 3 Credit Card Processing. Government agencies require Level 3 protection to make purchases using government purchase cards.

**Comment by creativewebgirl** [comment]
Yes with credit card we have to require the info but we need to give them the option of using a purchase order number to check out and then we will bill them for the amount.  Can you tell me what the native module is for this?  The reason we are using your extension is to integrate with PayTrace Merchant Account.
